name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller>=6.0
    
    - name: Build with PyInstaller
      run: |
        cd video_clips
        python -m PyInstaller ^
          --clean ^
          --noconfirm ^
          --onedir ^
          --windowed ^
          --name "VideoClipsApp" ^
          --add-data "config;config" ^
          --add-data "modules;modules" ^
          --add-data "utils;utils" ^
          --hidden-import "PyQt5.QtCore" ^
          --hidden-import "PyQt5.QtGui" ^
          --hidden-import "PyQt5.QtWidgets" ^
          --hidden-import "PyQt5.sip" ^
          --hidden-import "numpy" ^
          --hidden-import "PIL" ^
          --hidden-import "PIL.Image" ^
          --collect-submodules "PyQt5" ^
          --collect-submodules "numpy" ^
          --collect-submodules "PIL" ^
          main_qt5.py
    
    - name: Create Release Package
      run: |
        cd video_clips
        mkdir release
        xcopy /E /I dist\VideoClipsApp release\VideoClipsApp
        echo @echo off > release\run_app.bat
        echo cd /d "%%~dp0" >> release\run_app.bat
        echo cd VideoClipsApp >> release\run_app.bat
        echo VideoClipsApp.exe >> release\run_app.bat
        echo pause >> release\run_app.bat
    
    - name: Upload Release Artifact
      uses: actions/upload-artifact@v3
      with:
        name: VideoClipsApp-Windows
        path: video_clips/release/
        retention-days: 30

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pyqt5 python3-pyqt5.qtmultimedia
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller>=6.0
    
    - name: Build with PyInstaller
      run: |
        cd video_clips
        python -m PyInstaller \
          --clean \
          --noconfirm \
          --onedir \
          --windowed \
          --name "VideoClipsApp" \
          --add-data "config:config" \
          --add-data "modules:modules" \
          --add-data "utils:utils" \
          --hidden-import "PyQt5.QtCore" \
          --hidden-import "PyQt5.QtGui" \
          --hidden-import "PyQt5.QtWidgets" \
          --hidden-import "PyQt5.sip" \
          --hidden-import "numpy" \
          --hidden-import "PIL" \
          --hidden-import "PIL.Image" \
          --collect-submodules "PyQt5" \
          --collect-submodules "numpy" \
          --collect-submodules "PIL" \
          main_qt5.py
    
    - name: Create Release Package
      run: |
        cd video_clips
        mkdir -p release
        cp -r dist/VideoClipsApp release/
        cat > release/run_app.sh << 'EOF'
        #!/bin/bash
        cd "$(dirname "$0")"
        cd VideoClipsApp
        ./VideoClipsApp
        EOF
        chmod +x release/run_app.sh
    
    - name: Upload Release Artifact
      uses: actions/upload-artifact@v3
      with:
        name: VideoClipsApp-Linux
        path: video_clips/release/
        retention-days: 30